const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

function sanitizeReportText(text) {
  if (!text) {
    return "";
  }

  return String(text)
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/^\s*#+\s*/gm, "")
    .trim();
}

async function createPDF(report, scanId) {

  const reportsDir = path.join(__dirname, "../reports");
  const chartsDir = path.join(__dirname, "../charts");

  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir);
  }

  const filePath = path.join(reportsDir, `report_${scanId}.pdf`);
  const cleanedReport = sanitizeReportText(report);

  const doc = new PDFDocument({
    margin: 50
  });

  doc.pipe(fs.createWriteStream(filePath));
  doc
    .fontSize(22)
    .fillColor("#0b3d91")
    .text("CyberTech AI Security Report", {
      align: "center"
    });

  doc.moveDown(0.5);

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(`Scan ID: ${scanId}`, { align: "center" });

  doc.moveDown(2);
  doc
    .fontSize(12)
    .fillColor("black")
    .text(cleanedReport, {
      align: "left"
    });

  doc.moveDown(2);
  const chartPath = path.join(chartsDir, "vulnerability_pie.png");

  if (fs.existsSync(chartPath)) {

    doc.addPage();

    doc
      .fontSize(18)
      .text("Vulnerability Distribution", {
        align: "center"
      });

    doc.moveDown();

    doc.image(chartPath, {
      fit: [450, 350],
      align: "center"
    });

  }
  doc.addPage();

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      "Generated by CyberTech AI Vulnerability Management System",
      50,
      700,
      { align: "center" }
    );

  doc.end();

  return filePath;
}

module.exports = { createPDF };
